// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemetryCollector.Infrastructure.Database;

#nullable disable

namespace TelemetryCollector.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260504012124_AddLatencyBucket")]
    partial class AddLatencyBucket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelemetryCollector.Infrastructure.Database.Entities.AlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("TelemetryCollector.Infrastructure.Database.Entities.EndpointLatencyBucketEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EndPoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("BucketUpperBoundMs")
                        .HasColumnType("int");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.HasKey("ServiceName", "EndPoint", "WindowStart", "BucketUpperBoundMs");

                    b.HasIndex("ServiceName", "EndPoint", "WindowStart");

                    b.ToTable("EndpointLatencyBuckets");
                });

            modelBuilder.Entity("TelemetryCollector.Infrastructure.Database.Entities.EndpointMetricEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EndPoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientErrorRequests")
                        .HasColumnType("int");

                    b.Property<int>("ServerErrorRequests")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulRequests")
                        .HasColumnType("int");

                    b.Property<long>("TotalLatencyMs")
                        .HasPrecision(18, 3)
                        .HasColumnType("bigint");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int");

                    b.HasKey("ServiceName", "EndPoint", "WindowStart");

                    b.HasIndex("WindowStart");

                    b.ToTable("EndpointMetrics");
                });

            modelBuilder.Entity("TelemetryCollector.Infrastructure.Database.Entities.SlaPolicyEntity", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EndPoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxConsecutiveHealthFailures")
                        .HasColumnType("int");

                    b.Property<double>("MaxErrorRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<double>("MaxP95LatencyMs")
                        .HasPrecision(18, 3)
                        .HasColumnType("float(18)");

                    b.HasKey("ServiceName", "EndPoint");

                    b.ToTable("SlaPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
